name: tools.cross-ts.com
services:
  app:
    image: nginx:alpine
    volumes:
      - type: bind
        source: dist
        target: /usr/share/nginx/html
        read_only: true
    ports:
      - '127.0.0.1::80'
